development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: terence.victoria
  :password: p@ssw0rdz
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: terence.victoria
  :password: p@ss0wrdz
  :enable_starttls_auto: true